version: "3"

services:
    api:
        build:
            context: ./server/
            dockerfile: Dockerfile
        container_name: proxy-backend
        restart: unless-stopped
        ports:
            - 5000:5000
        environment:
            TZ: "Asia/Singapore"
            PORT: "5000"
            MODULE_NAME: "api.main"
            LOG_LEVEL: "debug"
            PRE_START_PATH: "/app/api/prestart.sh"
            # Gunicorn workers
            MAX_WORKERS: "2"
        volumes:
            - "./logs:/app/logs"
